import { Providers } from "@/components/providers/providers";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toaster";
import { Header } from "./_components/header";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const inter = Inter({ weight: ["300", "400", "500", "700"], subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
	title: "General",
	description: "Generated by create next app",
	icons: {
		icon: "/favicon.ico"
	}
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const session = await getServerSession(authOptions);
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={cn(inter.className, "font-medium")}>
				<Providers refetchOnWindowFocus={true} refetchWhenOffline={false} session={session}>
					<div className='wrapper flex min-h-screen flex-col overflow-hidden'>
						<Header />
						<main className='flex flex-auto flex-col pt-20'>{children}</main>
					</div>
				</Providers>
				<Toaster />
			</body>
		</html>
	);
}
